# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: check-added-large-files
      name: Check for files larger than 5 MB
      args: [ "--maxkb=5120" ]
    - id: end-of-file-fixer
      name: Check for a blank line at the end of scripts (auto-fixes)
      exclude: '\.Rd'
    - id: trailing-whitespace
      name: Check for trailing whitespaces (auto-fixes)
- repo: https://github.com/pycqa/isort
  rev: 7.0.0
  hooks:
    - id: isort
      name: isort - Sort Python imports (auto-fixes)
      args: ["--profile", "black", "--filter-files"]
- repo: https://github.com/psf/black
  rev: 25.9.0
  hooks:
    - id: black
      name: black - consistent Python code formatting (auto-fixes)
      language_version: python
- repo: https://github.com/PyCQA/flake8
  rev: 7.3.0
  hooks:
    - id: flake8
      name: flake8 - Python linting
      additional_dependencies: [Flake8-pyproject]
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.5.0
  hooks:
    - id: detect-secrets
      name: detect-secrets - Detect secrets in staged code
      args: [ "--baseline", ".secrets.baseline" ]
      exclude: .*/tests/.*|^\.cruft\.json$

